src/app/shared/components/date-filter/date-filter.component.html
src/app/shared/components/date-filter/date-filter.component.ts
src/app/shared/components/date-filter/date-filter.service.ts

https://kaltura.atlassian.net/browse/AN-69

AN-69 Save date and compare filter settings in the URL for deep linking

---

src/app/modules/audience/views/engagement/impressions/impressions.component.ts
src/app/shared/components/date-filter/date-filter.component.ts
src/app/shared/components/date-filter/date-filter.service.ts

https://kaltura.atlassian.net/browse/AN-106

AN-106 Date format issue with the period menu

---

src/app/modules/audience/views/geo-location/geo-location.component.html
src/app/modules/bandwidth/views/end-user/end-user-storage.component.html
src/app/modules/bandwidth/views/publisher-storage/publisher-storage.component.html

https://kaltura.atlassian.net/browse/AN-97
https://kaltura.atlassian.net/browse/AN-138

AN-97, AN-138

---

src/app/shared/components/date-filter/date-filter.component.html
src/app/shared/components/date-filter/date-filter.component.ts
src/app/shared/components/date-filter/date-filter.service.ts

https://kaltura.atlassian.net/browse/AN-65
https://kaltura.atlassian.net/browse/AN-184

AN-65, AN-184

---

src/app/modules/audience/views/engagement/top-videos/top-videos-table/top-videos-table.component.scss
src/app/modules/audience/views/engagement/top-videos/top-videos.component.ts

https://kaltura.atlassian.net/browse/AN-261

AN-261 Engagement:Top Videos:Screen is twisted when there is "No Data Found"

---

src/app/modules/audience/views/engagement/impressions/impressions.component.ts

https://kaltura.atlassian.net/browse/AN-264

AN-264 Audience - Engagement - Video engagement graph plays-through percentage calculation wrong

---

src/app/modules/audience/views/engagement/highlights/highlights.component.ts
src/app/modules/audience/views/engagement/impressions/impressions.component.ts
src/app/modules/audience/views/engagement/mini-highlights/mini-highlights.component.ts
src/app/modules/audience/views/engagement/mini-top-videos/mini-top-videos.component.ts
src/app/modules/audience/views/engagement/syndication/syndication.component.ts
src/app/modules/audience/views/engagement/top-videos/top-videos.component.ts
src/app/modules/audience/views/engagement/users/users.component.ts
src/app/modules/contributors/views/top-contributors/highlights/highlights.component.ts
src/app/modules/contributors/views/top-contributors/mini-highlights/mini-highlights.component.ts
src/app/modules/contributors/views/top-contributors/mini-top-contributors/mini-top-contributors.component.ts
src/app/modules/contributors/views/top-contributors/sources/sources.component.ts
src/app/modules/contributors/views/top-contributors/top-contributors/top-contributors.component.ts
src/app/modules/contributors/views/top-contributors/users/users.component.ts

https://kaltura.atlassian.net/browse/AN-269
https://kaltura.atlassian.net/browse/AN-270

AN-269, AN-270

---

src/app/modules/audience/views/engagement/highlights/highlights.config.ts
src/app/modules/audience/views/engagement/syndication/syndication-data.config.ts
src/app/shared/services/report.service.ts

https://kaltura.atlassian.net/browse/AN-256
https://kaltura.atlassian.net/browse/AN-279

AN-256, AN-279

---

src/app/modules/audience/views/engagement/engagement.component.scss
src/app/modules/audience/views/engagement/mini-top-videos/mini-top-videos.component.html
src/app/modules/audience/views/engagement/mini-top-videos/mini-top-videos.component.scss
src/app/modules/audience/views/engagement/mini-top-videos/mini-top-videos.component.ts
src/app/modules/audience/views/engagement/mini-top-videos/mini-top-videos.config.ts
src/app/modules/audience/views/engagement/top-videos/top-videos-data.config.ts
src/app/modules/audience/views/engagement/top-videos/top-videos-table/top-videos-table.component.html
src/app/modules/audience/views/engagement/top-videos/top-videos.component.ts
src/app/modules/contributors/views/top-contributors/mini-top-contributors/mini-top-contributors.component.scss
src/styles/styles.scss

also fixed https://kaltura.atlassian.net/browse/AN-314

Top videos score, AN-314

---

src/app/modules/audience/views/engagement/syndication/syndication.component.html
src/app/modules/audience/views/engagement/syndication/syndication.component.scss
src/app/modules/audience/views/engagement/syndication/syndication.component.ts
src/app/modules/audience/views/engagement/top-videos/top-videos-table/top-videos-table.component.html

https://kaltura.atlassian.net/browse/AN-395
https://kaltura.atlassian.net/browse/AN-398

AN-395, AN-398

---

src/app/shared/components/dropdown-filter/dropdown-filter.component.html
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-259
https://kaltura.atlassian.net/browse/AN-498

AN-259, AN-498

---

src/app/shared/components/horizontal-bar-row/horizontal-bar-row.component.scss

https://kaltura.atlassian.net/browse/AN-646

fix: horizontal bar chart styles

---

src/app/modules/audience/audience.module.ts
src/app/modules/audience/views/content-interactions/interactions/even-table-height.directive.ts
src/app/modules/audience/views/content-interactions/interactions/interactions-table/interactions-table.component.html
src/app/modules/audience/views/content-interactions/interactions/interactions-table/interactions-table.component.scss
src/app/modules/audience/views/content-interactions/interactions/interactions-table/interactions-table.component.ts
src/app/modules/audience/views/content-interactions/interactions/interactions.component.html
src/app/modules/audience/views/content-interactions/interactions/interactions.component.scss
src/app/modules/audience/views/content-interactions/interactions/interactions.component.ts
src/app/modules/audience/views/content-interactions/interactions/interactions.config.ts

https://kaltura.atlassian.net/browse/AN-647

chore: Update content interactions table & graph design

---

src/app/modules/entry/entry-view.component.html
src/app/modules/entry/entry.module.ts
src/app/modules/entry/views/video-performance/pipes/table-mode-icon.pipe.ts
src/app/modules/entry/views/video-performance/video-performance.component.html
src/app/modules/entry/views/video-performance/video-performance.component.scss
src/app/modules/entry/views/video-performance/video-performance.component.ts
src/app/modules/entry/views/video-performance/video-performance.config.ts
src/app/shared/services/report.service.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-630

feat(analytics/entry): As a user, I'd like to set the dimension for drill down in the details tab

---

src/app/modules/bandwidth/bandwidth.module.ts
src/app/modules/bandwidth/views/end-user/end-user-storage.component.html
src/app/modules/bandwidth/views/end-user/end-user-storage.component.scss
src/app/modules/bandwidth/views/end-user/end-user-storage.component.ts
src/app/modules/bandwidth/views/end-user/filter/filter.component.html
src/app/modules/bandwidth/views/end-user/filter/filter.component.scss
src/app/modules/bandwidth/views/end-user/filter/filter.component.ts
src/app/modules/bandwidth/views/publisher-storage/publisher-storage.component.html
src/app/modules/bandwidth/views/publisher-storage/publisher-storage.component.scss
src/app/modules/bandwidth/views/publisher-storage/publisher-storage.component.ts
src/app/shared/components/filter/filter.component.html
src/app/shared/components/filter/filter.component.ts
src/app/shared/components/filter/location-filter/location-filter.component.html
src/app/shared/components/filter/location-filter/location-filter.component.scss
src/app/shared/components/filter/location-filter/location-filter.component.ts

https://kaltura.atlassian.net/browse/AN-631

feat(usage/filter): filter the usage dashboard by different metrics

---

src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/views/live-devices/live-devices-request-factory.ts
src/app/modules/entry-live/views/live-devices/live-devices.config.ts
src/app/modules/entry-live/views/live-devices/live-devices.widget.ts
src/app/modules/entry-live/views/live-geo/live-geo-request-factory.ts
src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.component.ts
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/app/modules/entry-live/views/live-geo/live-geo.widget.ts
src/app/modules/entry-live/widgets/widgets-manager.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-670
https://kaltura.atlassian.net/browse/AN-671

AN-670, AN-671

---

src/app/modules/entry-live/views/live-discovery-chart/discovery-chart/discovery-chart.component.html
src/app/modules/entry-live/views/live-discovery-chart/discovery-chart/discovery-chart.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.component.ts

https://kaltura.atlassian.net/browse/AN-718

Preserve data zoom settings on metric change

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts

https://kaltura.atlassian.net/browse/AN-720

fix: graph values formatting

---

src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.widget.ts
src/app/shared/components/date-filter/date-filter-utils.ts

https://kaltura.atlassian.net/browse/AN-728

fix: resolution selector does not change the resolution of the graph

---

src/app/modules/entry-live/views/live-devices/live-devices-request-factory.ts
src/app/modules/entry-live/views/live-devices/live-devices.widget.ts

https://kaltura.atlassian.net/browse/AN-729

fix: incorrect devices users distribution calculation

---

src/app/shared/components/date-filter/date-filter-utils.ts

https://github.com/kaltura/analytics-front-end/tree/AN-549

fix start and end date server call parameters when start and end dates have different timezone offsets

---

src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/entry-live.module.ts
src/app/modules/entry-live/widgets/widget-base.ts

https://kaltura.atlassian.net/browse/AN-756

fix: provide widgets in component to flush data on navigate out

---

src/app/modules/entry-live/views/live-discovery-table/devices-table/devices-table.component.html
src/app/modules/entry-live/views/live-discovery-table/devices-table/live-discovery-devices-table.config.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-table.config.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/users-table.component.html

https://kaltura.atlassian.net/browse/AN-755

fix: update flavors value separator

---

src/app/modules/entry-live/views/live-discovery-table/devices-table/devices-table.component.html
src/app/modules/entry-live/views/live-discovery-table/devices-table/devices-table.component.ts
src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.widget.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/users-table.component.ts

https://kaltura.atlassian.net/browse/AN-771

fix(entry-live): reset discovery tables upon filters change

---

src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/app/modules/entry-live/views/live-geo/live-geo.widget.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-773

chore(entry-live): update geo report with new metrics

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.widget.ts

https://kaltura.atlassian.net/browse/AN-774

fix(entry-live): calculate buffering, dvr, engaged users footnote value

---

src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.html
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts

https://kaltura.atlassian.net/browse/AN-767

fix(discovery/custom-time-selector): check time inputs for the same day only

---

src/app/modules/entry-live/views/live-discovery-table/devices-table/live-discovery-devices-table-provider.ts
src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.widget.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-status-request-factory.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-table-provider.ts

https://kaltura.atlassian.net/browse/AN-784

fix(discovery/status): update summary status date range

---

src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.component.html
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.html
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.service.ts
src/app/modules/entry-live/views/live-discovery-table/filter/filter.component.html
src/app/modules/entry-live/views/live-discovery-table/filter/filter.component.scss
src/app/modules/entry-live/views/live-discovery-table/filter/filter.component.ts
src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.component.html
src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.component.scss
src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.component.ts
src/assets/i18n/en.json
src/styles/styles.scss

https://kaltura.atlassian.net/browse/AN-785

feat(discovery/table): add selected date range label in table header

---

src/app/modules/audience/views/geo-location/geo-location.component.ts
src/app/modules/entry/views/top-countries/top-countries.component.ts
src/app/shared/services/report-helper.ts
src/app/shared/utils/parse-fomated-value.ts

[SUP-18908](https://kaltura.atlassian.net/browse/SUP-18908)
also might be a fix for [SUP-18915](https://kaltura.atlassian.net/browse/SUP-18915)
Reference for the list of separators: [wiki](https://en.wikipedia.org/wiki/Decimal_separator#Unicode_characters)

fix: handle parsed numbers values regardless of locale

---

src/app/modules/entry-live/components/toggle-live/toggle-live.component.html
src/app/modules/entry-live/components/toggle-live/toggle-live.component.scss
src/app/modules/entry-live/components/toggle-live/toggle-live.component.ts
src/app/modules/entry-live/components/toggle-live/toggle-live.service.ts
src/app/modules/entry-live/entry-live-view.component.html
src/app/modules/entry-live/entry-live-view.component.scss
src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/entry-live.module.ts
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.ts
src/app/shared/services/browser.service.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-792

feat(entry-live): add toggle live button

---

src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.component.ts

https://kaltura.atlassian.net/browse/AN-816

fix(entry-live/export): set relevant export date in non-preset mode

---

src/app/app.component.ts
src/app/modules/audience/views/engagement/engagement.component.html
src/app/modules/audience/views/engagement/mini-highlights/mini-highlights.component.html
src/app/modules/audience/views/engagement/mini-highlights/mini-highlights.component.scss
src/app/modules/audience/views/engagement/mini-highlights/mini-highlights.component.ts
src/app/modules/audience/views/engagement/top-videos/top-videos.component.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-689

feat: add played entries count

---

src/app/modules/audience/views/geo-location/geo-location.component.html
src/app/modules/audience/views/geo-location/geo-location.component.scss
src/app/modules/audience/views/geo-location/geo-location.component.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-629

feat(engagement/geo): add ability to chose table mode

---

src/app/shared/components/filter/filter.component.ts

https://kaltura.atlassian.net/browse/AN-699

 fix(AN-699): update layout on open/close filters

---

src/app/modules/audience/views/engagement/highlights/entries-table/entries-table.component.ts

https://kaltura.atlassian.net/browse/AN-838

fix(AN-837): fix engagement entries table report type

---

src/app/modules/audience/views/engagement/highlights/highlights.component.ts

https://kaltura.atlassian.net/browse/AN-837

fix(AN-837): preserve secondary engagement user filter

---

src/app/shared/utils/table-local-sort-handler.ts

https://kaltura.atlassian.net/browse/AN-842

fix(AN-842): handle date parsing in table sort function

---

src/app/modules/entry/views/entry-preview/entry-preview.component.html
src/app/modules/entry/views/entry-preview/entry-preview.component.scss
src/app/modules/entry/views/entry-preview/entry-preview.component.ts
src/app/modules/entry/views/entry-preview/entry-preview.config.ts
src/assets/i18n/en.json
src/styles/styles.scss

https://kaltura.atlassian.net/browse/AN-849

feat(entry-drill-down): add unique users graph line

---

src/app/shared/components/date-filter/date-filter.component.ts

https://kaltura.atlassian.net/browse/AN-872

fix(AN-872): reset sinceCreation date filter if no date provided

---

src/app/modules/audience/views/engagement/top-videos/top-videos-table/top-videos-table.component.html
src/app/modules/audience/views/engagement/top-videos/top-videos-table/top-videos-table.component.ts
src/app/modules/audience/views/engagement/top-videos/top-videos.component.html
src/app/modules/audience/views/engagement/top-videos/top-videos.component.ts

https://kaltura.atlassian.net/browse/SUP-19170

feat(SUP-19170): support sorting in engagement top videos table

---

src/app/modules/contributors/views/top-contributors/mini-top-contributors/mini-top-contributors.component.ts
src/app/modules/contributors/views/top-contributors/top-contributors/top-contributors.component.ts

https://kaltura.atlassian.net/browse/AN-899

fix(AN-899): set dates labels in compare mode on contributors page

---

src/app/modules/bandwidth/views/end-user/end-user-storage.component.ts

https://kaltura.atlassian.net/browse/AN-911

fix(AN-911): reapply users filter after drill up

---

src/app/modules/entry-live/views/live-discovery-chart/metrics-selector/metrics-selector-dropdown/metrics-selector-dropdown.component.scss

https://kaltura.atlassian.net/browse/AN-904

fix(entry-live/explore): remove scroll from metrics selector dropdown

---

src/app/modules/audience/views/engagement/highlights/entries-table/entries-table.component.ts
src/app/modules/audience/views/engagement/highlights/users-table/users-table.component.ts
src/app/modules/audience/views/engagement/highlights/users-table/users-table.config.ts
src/app/modules/entry/views/user-engagement/user-engagement.component.ts
src/app/modules/entry/views/user-engagement/user-engagement.config.ts

https://kaltura.atlassian.net/browse/AN-925
https://kaltura.atlassian.net/browse/AN-929

fix(AN-925,AN-929): use navigationDrilldown service to drilldown

---

src/app/modules/user/views/user-mini-top-content/user-mini-top-content.component.scss
src/app/modules/user/views/user-mini-top-content/user-mini-top-content.component.ts

https://kaltura.atlassian.net/browse/AN-928

fix(AN-928): mini top videos wide layout

---

src/app/modules/entry-live/entry-live-view.component.html
src/app/modules/entry-live/entry-live-view.component.scss
src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/views/live-devices/live-devices-request-factory.ts
src/app/modules/entry-live/views/live-devices/live-devices.component.html
src/app/modules/entry-live/views/live-devices/live-devices.component.ts
src/app/modules/entry-live/views/live-devices/live-devices.widget.ts
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.html
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.scss
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.scss
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.service.ts
src/app/modules/entry-live/views/live-geo/live-geo-request-factory.ts
src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.component.scss
src/app/modules/entry-live/views/live-geo/live-geo.component.ts
src/app/modules/entry-live/views/live-geo/live-geo.widget.ts
src/app/modules/entry-live/widgets/widget-base.ts

https://kaltura.atlassian.net/browse/AN-898

feat(entry-live): apply date filter to geo and devices reports

---

src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.html
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.service.ts
src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.component.ts
src/app/modules/entry-live/widgets/widget-base.ts

https://kaltura.atlassian.net/browse/AN-939
https://kaltura.atlassian.net/browse/AN-940

fix(AN-939, AN-940): update date range label every tick

---

src/app/modules/user/views/user-totals/user-totals.component.ts
src/app/modules/user/views/user-totals/user-totals.config.ts
src/app/shared/services/trend.service.ts

https://kaltura.atlassian.net/browse/AN-972

fix(AN-972): handle likes forbidden error

---

src/app/modules/audience/views/content-interactions/interactions/interactions.config.ts
src/app/modules/audience/views/content-interactions/mini-top-shared/mini-top-shared.config.ts
src/app/modules/audience/views/engagement/highlights/entries-table/entries-table.config.ts
src/app/modules/audience/views/engagement/highlights/users-table/users-table.config.ts
src/app/modules/audience/views/engagement/mini-top-videos/mini-top-videos.config.ts
src/app/modules/audience/views/engagement/top-videos/top-videos-data.config.ts
src/app/modules/contributors/views/top-contributors/mini-top-contributors/mini-top-contributors.config.ts
src/app/modules/contributors/views/top-contributors/top-contributors/top-contributors-data.config.ts
src/app/modules/entry/views/user-engagement/user-engagement.config.ts
src/app/modules/live/views/entries-live/entries-live-data.config.ts

https://kaltura.atlassian.net/browse/AN-974

fix(AN-974): prevent partner id be compared

---

src/app/app.component.ts
src/app/modules/user/user-view.component.ts

https://kaltura.atlassian.net/browse/AN-936
Depends on https://github.com/kaltura/kmc-ng/pull/865

feat(AN-936): preselect tab according to previous route

---

src/app/modules/user/views/user-mini-highlights/devices/devices.component.html
src/app/modules/user/views/user-mini-highlights/devices/devices.component.scss
src/app/modules/user/views/user-mini-highlights/devices/devices.component.ts
src/app/modules/user/views/user-mini-highlights/user-mini-highlights.component.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-941

feat(AN-941): show top 2 devices

---

src/app/modules/contributors/views/top-contributors/components-list.ts
src/app/modules/contributors/views/top-contributors/filter/filter.component.html
src/app/modules/contributors/views/top-contributors/filter/filter.component.scss
src/app/modules/contributors/views/top-contributors/filter/filter.component.ts
src/app/modules/contributors/views/top-contributors/top-contributors.component.html

https://kaltura.atlassian.net/browse/AN-510

fix(AN-510): remove geo filters for contributors

---

src/app/app.component.ts
src/app/modules/user/user-view.component.ts

https://kaltura.atlassian.net/browse/AN-914
@amirch1 this is not a complete PR, I'm currently not sure how to determine when we need to switch account or not, please advise.
NOTE: don't use activated route service since this code will be moved to the app service where the activated route is not available

WIP feat(AN-914): navigate to the default page when switching multiaccount

---

src/app/modules/entry/views/entry-preview/entry-preview.component.ts

https://kaltura.atlassian.net/browse/AN-916

fix(entry/views-graph): handle empty results for current table

---

src/app/modules/audience/views/engagement/engagement-export.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/SUP-19600

feat(SUP-19600): add users engagement export

---

src/app/modules/user/views/user-highlights/highlights.component.ts
src/app/modules/user/views/user-media-upload/user-media-upload.component.ts
src/app/modules/user/views/user-mini-top-content/user-mini-top-content.component.ts
src/app/modules/user/views/user-top-content/top-content-table/top-content-table.component.ts

https://kaltura.atlassian.net/browse/AN-1008
@amirch1 it seems an easy fix, but I'm not totally sure why we set `includeQueryParams` to `false` in the first place, so I'm creating a PR to let you double-check it

fix(AN-1008): preserve query params upon drilldown

---

src/app/modules/entry-live/views/live-discovery-chart/discovery-chart/discovery-chart.component.ts

https://kaltura.atlassian.net/browse/AN-978

feat(AN-978): normalize the latency metric

---

src/app/modules/bandwidth/views/end-user/filter/filter.component.html
src/app/modules/bandwidth/views/publisher-storage/publisher-storage.component.html
src/app/shared/components/dropdown-filter/dropdown-filter.component.html
src/app/shared/components/filter/filter.component.html
src/app/shared/components/filter/filter.component.ts
src/app/shared/components/filter/location-filter/location-filter.component.html
src/app/shared/components/filter/location-filter/location-filter.component.scss
src/app/shared/components/filter/location-filter/location-filter.component.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-698

fix(AN-698): remove location filter in end-user, add note to bw storage

---

src/app/modules/entry-live/views/live-discovery-chart/discovery-chart/discovery-chart.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts
src/app/modules/entry-live/views/live-discovery-chart/metrics-selector/metrics-selector-dropdown/metrics-selector-dropdown.component.html
src/app/modules/entry-live/views/live-discovery-chart/metrics-selector/metrics-selector.component.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-977

feat(AN-977): allow select none metric in discovery graph

---

src/app/modules/audience/views/engagement/highlights/entries-table/entries-table.component.html
src/app/modules/audience/views/engagement/highlights/entries-table/entries-table.component.ts
src/app/modules/audience/views/engagement/highlights/highlights.component.html
src/app/modules/audience/views/engagement/highlights/highlights.component.ts
src/app/modules/audience/views/engagement/highlights/users-table/users-table.component.ts
src/app/shared/components/entry-engagement-filter/entries-filter/entries-filter.component.ts
src/app/shared/components/entry-engagement-filter/entry-engagement-filter.component.html
src/app/shared/components/entry-engagement-filter/entry-engagement-filter.component.scss
src/app/shared/components/entry-engagement-filter/entry-engagement-filter.component.ts
src/app/shared/components/filter/filter.component.ts
src/app/shared/shared.module.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-962

feat(AN-962): add engagement -> entries filter

---

src/app/shared/components/export-csv/export-csv.component.scss

https://kaltura.atlassian.net/browse/AN-1029

fix(AN-1029): hide group node checkbox

---

src/app/modules/entry/entry-view.component.ts

https://kaltura.atlassian.net/browse/SUP-19847

SUP-19847: show entry analytics for entries owned by deleted users

---

src/app/modules/entry-live/entry-live-view.component.ts
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.ts
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.service.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts

https://kaltura.atlassian.net/browse/AN-1040

feat(AN-1040): set default date range to 5 min

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts

https://kaltura.atlassian.net/browse/AN-1033

feat(AN-1033): add bitrate metric

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-975

feat(AN-975): add avg buffering metric

---

src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1044

feat(AN-1044): replace avg buffering metric

---

src/app/shared/components/syndication-report/syndication.component.scss

https://kaltura.atlassian.net/browse/AN-1039

fix(AN-1039): syndication icon

---

src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-959

feat(AN-959): update buffering metric in geo

---

src/app/shared/components/impressions-report/impressions.component.scss

https://kaltura.atlassian.net/browse/AN-1038

fix(AN-1038): impressions dropdown width

---

src/app/modules/audience/views/engagement/highlights/entries-table/entries-table.component.ts

https://kaltura.atlassian.net/browse/AN-1032

fix(AN-1032): reset entries total count

---

src/app/modules/entry-live/entry-live-export.config.ts

https://kaltura.atlassian.net/browse/AN-1034

feat(AN-1034): update export config

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts

https://kaltura.atlassian.net/browse/AN-1043

feat(AN-1043): remove buffering users metric

---

src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-table.config.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/users-table.component.html
src/app/modules/entry-live/views/live-discovery-table/users-table/users-table.component.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1041

feat(AN-1041): replace users buffering with buffer rate

---

src/app/modules/entry-live/views/live-discovery-chart/filters/filters.component.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.service.ts
src/app/modules/entry-live/views/live-discovery-table/table-selector/table-selector.component.scss
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/WEBC-1675

fix(WEBC-1675): small resolution support for filter row

---

src/app/modules/user/views/user-highlights/highlights.component.html
src/app/shared/components/report-tabs/report-tabs.component.html
src/app/shared/components/report-tabs/report-tabs.component.ts

https://kaltura.atlassian.net/browse/AN-1048

add narrowTabs property to tabs component

---

src/app/modules/entry-live/views/live-discovery-table/devices-table/live-discovery-devices-table-provider.ts
src/app/modules/entry-live/views/live-discovery-table/devices-table/live-discovery-devices-table.config.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-table.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1046

feat(AN-1046): update user buffering calculation

---

src/app/modules/user/views/user-highlights/highlights.component.ts
src/app/modules/user/views/user-highlights/highlights.config.ts
src/app/modules/user/views/user-highlights/table/table.component.html
src/app/shared/components/syndication-report/syndication-data.config.ts
src/app/shared/components/syndication-report/syndication.component.html
src/app/shared/components/syndication-report/syndication.component.ts

https://kaltura.atlassian.net/browse/AN-1052

fix(AN-1052): rearrange metrics

---

src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.html
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.scss
src/app/modules/entry-live/views/live-discovery-chart/time-selector/time-selector.component.ts

https://kaltura.atlassian.net/browse/AN-759

fix AN-759

---

src/app/modules/entry-live/views/live-discovery-table/live-discovery-table.widget.ts

https://kaltura.atlassian.net/browse/AN-1061

fix(AN-1061): set default provider and filters

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.widget.ts
src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.component.ts
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/app/modules/entry-live/views/live-geo/live-geo.widget.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-959

fix(AN-969): switch users metric

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.config.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery.widget.ts
src/app/modules/entry-live/views/live-users/live-users.widget.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-949
https://kaltura.atlassian.net/browse/AN-843
https://kaltura.atlassian.net/browse/AN-1064

fix graph footnote and users engagement metrics calculation

---

src/app/modules/entry-live/views/live-geo/live-geo.component.html

https://kaltura.atlassian.net/browse/AN-1067

fix(AN-1067): remove active users from the table

---

src/app/modules/entry-live/views/live-geo/live-geo.widget.ts

https://kaltura.atlassian.net/browse/AN-1065

fix(AN-1065): preserve geo filter

---

src/app/modules/entry-live/views/live-discovery-table/devices-table/live-discovery-devices-table.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1076

fix(AN-1076): use correct metric in devices table

---

src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.component.ts
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/app/modules/entry-live/views/live-geo/live-geo.widget.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1072

fix(AN-1072): use views metric in geo map report

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.widget.ts

https://kaltura.atlassian.net/browse/AN-1080

fix(AN-1080): restore date filter from dateRange

---

src/app/modules/entry-live/views/live-bandwidth/live-bandwidth-request-factory.ts
src/app/modules/entry-live/views/live-devices/live-devices-request-factory.ts
src/app/modules/entry-live/views/live-discovery-chart/filters/filters.service.ts
src/app/modules/entry-live/views/live-discovery-chart/live-discovery-request-factory.ts
src/app/modules/entry-live/views/live-discovery-table/devices-table/live-discovery-devices-table-request-factory.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-status-request-factory.ts
src/app/modules/entry-live/views/live-discovery-table/users-table/live-discovery-users-table-request-factory.ts
src/app/modules/entry-live/views/live-geo/live-geo-request-factory.ts
src/app/modules/entry-live/views/live-users/live-users-request-factory.ts
src/app/shared/utils/get-fixed-epoch.ts

https://kaltura.atlassian.net/browse/AN-1077

fix(AN-1077): round toDate to nearest 10 sec

---

src/app/modules/entry-live/views/live-geo/live-geo-request-factory.ts
src/app/modules/entry-live/views/live-geo/live-geo.component.html
src/app/modules/entry-live/views/live-geo/live-geo.component.ts
src/app/modules/entry-live/views/live-geo/live-geo.config.ts
src/app/modules/entry-live/views/live-geo/live-geo.widget.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1089

fix(AN-1089): display active users in auth mode, fix distribution calc

---

src/app/modules/entry-live/views/live-geo/live-geo.widget.ts

https://kaltura.atlassian.net/browse/AN-1092

fix(AN-1092): update geo table sorting

---

src/app/modules/entry/views/image/entry-view.component.html
src/app/modules/entry/views/image/entry-view.component.ts

https://kaltura.atlassian.net/browse/AN-1107

fix(AN-1107): use setter to update entry

---

src/app/modules/entry/views/image/image-performance/image-performance.component.ts

https://kaltura.atlassian.net/browse/AN-1118

AN-1118 - clear compare metric upon tab change

---

src/app/shared/services/compare.service.ts

https://kaltura.atlassian.net/browse/AN-1117

fix(AN-1117): compare to metric dots color

---

src/app/modules/audience/views/engagement/highlights/dates-table/dates-table.component.html
src/app/modules/audience/views/engagement/highlights/dates-table/dates-table.component.ts
src/app/modules/audience/views/engagement/highlights/highlights.component.html
src/app/modules/audience/views/engagement/highlights/highlights.component.ts

https://kaltura.atlassian.net/browse/AN-1121

AN-1121 - pass sorting field according to selected time unit

---

src/app/modules/entry/views/shared/top-countries/geo/geo.component.html
src/app/modules/entry/views/shared/top-countries/geo/geo.component.ts
src/app/modules/entry/views/shared/top-countries/top-countries.config.ts

https://kaltura.atlassian.net/browse/AN-1122

fix Geo report for entries with impressions and 0 plays

---

src/app/shared/pipes/category-full-name.pipe.ts

https://kaltura.atlassian.net/browse/AN-1142

fix(AN-1142): category full name pipe – remove last chunk

---

src/app/modules/entry/views/image/image-performance/image-performance.component.html
src/app/modules/entry/views/shared/context-table/context-table.component.ts
src/app/modules/entry/views/video/video-performance/video-performance.component.html
src/app/modules/entry/views/video/video-performance/video-performance.component.ts

https://kaltura.atlassian.net/browse/AN-1143

fix(AN-1143): pass entryId to context table

---

src/app/modules/entry-live/views/live-discovery-chart/live-discovery.widget.ts

https://kaltura.atlassian.net/browse/AN-1080

fix(AN-1080): init original date event

---

src/app/modules/bandwidth/views/publisher-storage/publisher-storage-data.config.ts
src/assets/i18n/en.json

https://kaltura.atlassian.net/browse/AN-1180

set publisher storage units to MB or GB according to value in graph and table

---

src/app/modules/category/views/performance/performance.component.ts
src/app/modules/category/views/performance/users-table/users-table.component.ts

Fix for: https://kaltura.atlassian.net/browse/AN-22434

Category: Display user name instead of user ID in performance table > user drill-down AN-22434

---

package-lock.json
package.json
src/app/app-routing/app-routing.module.ts
src/app/modules/export/export.component.html
src/app/modules/export/export.component.scss
src/app/modules/export/export.component.ts
src/app/modules/export/export.module.ts
src/app/modules/export/export.routes.ts
src/app/shared/components/export-csv/export-csv.component.ts
src/assets/i18n/en.json
src/configuration/analytics-config.ts
src/configuration/host-routing-mapping.ts

feat(export): new export logic

feat(export): New export logic to prevent KS usage in email
